last_change = 2026-09-10T18:36:01.089193Z
addr = 0x776a0
size = 0xd5
name = "SDL_PerformWarpMouseInWindow"
type = "float *"

[header]
name = "SDL_PerformWarpMouseInWindow"
addr = 0x776a0
type = "float *"

[header.args]
